export enum UserConfigTypeDto {
  STRING = 'STRING',
  INTEGER = 'INTEGER',
  FLOAT = 'FLOAT',
  BOOLEAN = 'BOOLEAN',
  LIST = 'LIST',
  MAPPING = 'MAPPING',
  ENUM = 'ENUM',
  DATE = 'DATE',
  PIPELINE = 'PIPELINE',
  STEP = 'STEP',
  CONFIGURATION = 'CONFIGURATION',
}
